language: go

go:
  - 1.3

env:
  matrix:
    - secure: pftbTgwc/c93m3/3KHrF1J45Fw52+VcgYowD6NXQ2sCVBcTr51fFm94qM3tCkm7+aig+6c484x/DVE4BS2Sy/3FjB2JvWnPnfxGK6BDGBcl5yBHzJbC//Wk3QrYnxVNoIoe4SNRs4qmNXBnxaEnFqSMSs+VmzWpD/lrz4y7/jeE=
  global:
    secure: EN1zxl/wh0NSSwP3g/hzPO4z+v3EFOP6CdliuG3+Hulu88v9Yn19ewAeueAJ2nSUj/lrrMtTCnSQbxn9rBV23bSbh6l9fNPUUwYRfeJjxsqkoqJclywq/1epqt1UL1ofeCltzYDJTqLG3qOU+UlCeBFep0bcOQmO0r7hOSyiYHs=

install:
  - go get github.com/garyburd/redigo/redis
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

notifications:
  email:
    recipients:
      - rafael@justo.net.br
    on_success: change
    on_failure: always
