language: go

go:
  - 1.3

install:
  - go get github.com/garyburd/redigo/redis
  - go get code.google.com/p/go.tools/cmd/cover

script:
  - go test

notifications:
  email:
    recipients:
      - rafael@justo.net.br
    on_success: change
    on_failure: always
